### ISSUE TITLE
Known inventory issues

### ISSUE THREAD

**Issue by itsKline** [Chxttr/lj-inventory-with-QBCore-exports-and-decay#1]
- Dragging items makes them flash away and reappear with the quality/decay bar missing.
- Dragging items makes the hotbar 1-5 disappear.
- When leaving server and joining back, your inventory is wiped.

If I find more, I will update this list.

**Comment by Chxttr** [comment]
When leaving server and joining back, your inventory is wiped.
Fixed in README

Dragging items makes the hotbar 1-5 disappear.
Fixed
